module.exports = {
  trending: require("./Components/Surface/trending.js"),
  spotlight: require("./Components/Surface/spotlight.js"),
  updated: require("./Components/Surface/updated.js"),
  latest: require("./Components/Surface/latest.js"),
  topAiring: require("./Components/Surface/airing.js"),
  airing: require("./Components/Surface/airing.js"),
  ongoing: require("./Components/Surface/airing.js"),
  popular: require("./Components/Surface/popular.js"),
  mostFavourite: require("./Components/Surface/favoutite.js"),
  favourite: require("./Components/Surface/favoutite.js"),
  completed: require("./Components/Surface/completed.js"),
  genere: require("./Components/Depth/generes.js"),
  movies: require("./Components/Depth/movies.js"),
  ona: require("./Components/Depth/ona.js"),
  ova: require("./Components/Depth/ova.js"),
  specials: require("./Components/Depth/specials.js"),
  tv: require("./Components/Depth/tv.js"),
  dubbed: require("./Components/Depth/dubbed.js"),
  subbed: require("./Components/Depth/subbed.js"),
  search: require("./Components/Search/search.js"),
  details: require("./Components/Search/animeDetails.js"),
};
